version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'web'
    hostname: 'web'
    ports:
      - ${SERVER_PORT}:80
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
    # $需要转义
    command: /bin/bash -c "envsubst '$$API_HOST $$API_PORT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
